apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-job
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      containers:
      - name: dj-container
        image: dj_app
        command: ['python', 'manage.py', 'migrate', '--noinput']
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: dj-config
      restartPolicy: Never
  backoffLimit: 4
