apiVersion: v1
kind: ConfigMap
metadata:
  name: dj-config
data:
  DATABASE_URL: postgres://test_k8s:OwOtBep9Frut@my-release-postgresql:5432/test_k8s
  SECRET_KEY: secret-key
  DEBUG: 'True'
  ALLOWED_HOSTS: star-burger.test
